class DbTables {
  static const createUserTable = '''
    CREATE TABLE IF NOT EXISTS iUser(
        	SrNo integer primary key autoincrement,
        	UserId varchar,
        	UserName varchar,
        	UserEmailID varchar,
        	PhoneNo varchar,
        	UserPin varchar,
        	AuthType varchar,
        	LastAccessDate varchar,
        	RememberLogin varchar,
        	Password varchar,
        	UserStatus varchar,
        	memcode varchar,
        	Bizsrc varchar,
        	Chncls varchar,
        	CmsUnitCode varchar,
        	BranchName varchar,
        	Createddtim varchar,
        	Createdby varchar,
        	change_ver varchar,
        	TokenId varchar,
          UserType varchar,
          DashboardUpdatedDate varchar,
          CalendarUpdatedDate varchar,
          MobileNo varchar,
          EmailID varchar,
          Privacy_Flag varchar,
          Schedule_Days varchar,
          Ren_Rem_Days varchar
        );
  ''';

  static const dropUserTable = '''
    DROP TABLE IF EXISTS iUser
  ''';

  static const createTbl_DashboardData_Mob = '''
    CREATE TABLE IF NOT EXISTS DashboardData_Mob(
            RecId integer primary key autoincrement,
            UserId TEXT,
            AgentCode TEXT,
            AgentName TEXT,
            HNINCode TEXT,
            HNINName TEXT,
            LOBCode TEXT,
            ProdCode TEXT,
            NCBFlag TEXT,
            date TEXT,
            DateInLong LONG,
            TotalLeads TEXT,
            WIPLeads TEXT,
            LeadConverted TEXT,
            LeadLost TEXT,
            Lead_Converted TEXT,
            Premium_Collected TEXT,
            Policy_Issued TEXT,
            Call_Back TEXT,
            Appointment_Fixed TEXT,
            Non_Contactable TEXT,
            Lost_To_Competition TEXT,
            Customer_Not_Interested TEXT,
            Customer_Not_Responding TEXT,
            ParkLead TEXT,
            FollowUp TEXT,
            LeadType TEXT,
            BizType TEXT,
            MarcketType TEXT,
            PolicyChanel TEXT,
            BMCMCode TEXT,
            ircCode TEXT,
            ircname TEXT,
            RNType TEXT,
            NetODPremium TEXT,
            NetTPPremium TEXT,
            RNblockReason TEXT,
            ProductGroup TEXT,
            ProductSubCategory TEXT,
            NILDep TEXT,
            Category TEXT,
            FuelType TEXT,
            VehicleType TEXT,
            SeatingCapacity TEXT,
            AgeGroup TEXT,
            FamilySize TEXT,
            SumInsuredBand TEXT,
            PreExiting TEXT,
            Occupancy TEXT,
            SumInsured TEXT,
            LifeGroup TEXT,
            Zone TEXT,
            Region TEXT,
            RenewalYearCount TEXT,
            Preferred TEXT,
            Activity TEXT,
            SubActivity TEXT,
            Amount TEXT,
            SMName TEXT,
            SMBranch TEXT,
            SMBranchName TEXT,
            CreatedBy TEXT,
            CreateDTime TEXT,
            UpdatedBy TEXT,
            UpdatedDtime TEXT,
            MothYear TEXT,
            ReferenceNo varchar,
            SyncStatus varchar
          );
''';

  static const dropDashboardData_Mob = '''
    DROP TABLE IF EXISTS DashboardData_Mob
  ''';

  static const createTbl_CalendarData_Mob = '''
    CREATE TABLE IF NOT EXISTS CalendarData_Mob(
            RecId integer primary key autoincrement,
            UserId TEXT,
            AgentCode TEXT,
            AgentName TEXT,
            HNINCode TEXT,
            HNINName TEXT,
            LOBCode TEXT,
            ProdCode TEXT,
            NCBFlag TEXT,
            date TEXT,
            DateInLong LONG,
            TotalLeads TEXT,
            WIPLeads TEXT,
            LeadConverted TEXT,
            LeadLost TEXT,
            LeadType TEXT,
            BizType TEXT,
            MarcketType TEXT,
            PolicyChanel TEXT,
            BMCMCode TEXT,
            ircCode TEXT,
            ircname TEXT,
            RNType TEXT,
            NetODPremium TEXT,
            NetTPPremium TEXT,
            RNblockReason TEXT,
            ProductGroup TEXT,
            ProductSubCategory TEXT,
            NILDep TEXT,
            Category TEXT,
            FuelType TEXT,
            VehicleType TEXT,
            SeatingCapacity TEXT,
            AgeGroup TEXT,
            FamilySize TEXT,
            SumInsuredBand TEXT,
            PreExiting TEXT,
            Occupancy TEXT,
            SumInsured TEXT,
            LifeGroup TEXT,
            Zone TEXT,
            Region TEXT,
            RenewalYearCount TEXT,
            Preferred TEXT,
            SMName TEXT,
            SMBranch TEXT,
            SMBranchName TEXT,
            CreatedBy TEXT,
            CreateDTime TEXT,
            UpdatedBy TEXT,
            UpdatedDtime TEXT,
            mdate varchar,
            ReferenceNo varchar,
            SyncStatus varchar);
''';

  static const dropCalendarData_Mob = '''
    DROP TABLE IF EXISTS CalendarData_Mob
  ''';

  static const ceadDetails = '''
CREATE TABLE IF NOT EXISTS LeadDetails(
    RecId integer primary key autoincrement,
    SrvcReqDtlCode varchar,
    SrvcGrpCode varchar,
    CltCode varchar,
    AgentCode varchar,
    UserId varchar,
    ReqChannelId varchar,
    ReqChannel varchar,
    LOBCode varchar,
    LOB varchar,
    ProdCode varchar,
    ProdName varchar,
    CRMStatus varchar,
    LMSStatusDesc varchar,
    WFStatus varchar,
    WFStatDesc varchar,
    LeadSource varchar,
    LeadSourceDesc varchar,
    LeadSubSource varchar,
    LeadSubSourceDesc varchar,
    BusinessType varchar,
    BusinessTypeDesc varchar,
    LeadQueue varchar,
    LeadQueueDesc varchar,
    leadAmt varchar,
    TypeFlag varchar,
    LeadTypeDesc varchar,
    LeadStatusCode varchar,
    ActivityStatus varchar,
    CustPriority varchar,
    CustPriorityDesc varchar,
    SaleType varchar,
    SaleTypeDesc varchar,
    CreatedBy varchar,
    CreateDTim varchar,
    UpdatedBy varchar,
    UpdateDTim varchar,
    Remark varchar,
    ProposalNo varchar,
    PolicyNo varchar,
    PolicyStatus varchar,
    PolicyStartDate varchar,
    PolicyEndDate varchar,
    IssBranchCode varchar,
    IssBranchName varchar,
    InstallmentPrem varchar,
    PrevPolicyNo varchar,
    PrevPolicyInsCompName varchar,
    ProdClassCode varchar,
    ProdClassName varchar,
    ChassisNo varchar,
    EngineNo varchar,
    RegistrationNo varchar,
    Make varchar,
    Model varchar,
    PlanName varchar,
    AgentName varchar,
    HNINCode varchar,
    HNINName varchar,
    PolNCB varchar,
    Name varchar,
    MobileTel varchar,
    WorkTel varchar,
    Email varchar,
    AddrType varchar,
    Addr1 varchar,
    Addr2 varchar,
    Addr3 varchar,
    CityCode varchar,
    DistrictCode varchar,
    StateCode varchar,
    PinCode varchar,
    CountryCode varchar,
    Area varchar,
    isInserted varchar,
    IsUpdated varchar,
    TempSrvcReqDtlCode varchar,
    SyncStatus varchar,
    isWarmTransfer varchar,
    SrvcCommentType varchar,
    SrvcComments varchar,
    SrvcFromDTim varchar,
    Breaking varchar,
    LeadRating varchar,
    isOwner varchar,
    OwnerName varchar,
    AssignedTo varchar,
    AssignedToName varchar,
    CustTypeDesc varchar,
    LeadAging varchar,
    TelesaleActivity varchar,
    TelesaleActivityDoneBy varchar,
    TelesaleActivityDate varchar,
    TelesaleRemark varchar,
    LeadType TEXT,
    BizType TEXT,
    MarcketType TEXT,
    PolicyChanel TEXT,
    BMCMCode TEXT,
    ircCode TEXT,
    ircname TEXT,
    RNType TEXT,
    NetODPremium TEXT,
    NetTPPremium TEXT,
    RNblockReason TEXT,
    ProductGroup TEXT,
    ProductSubCategory TEXT,
    NILDep TEXT,
    Category TEXT,
    FuelType TEXT,
    VehicleType TEXT,
    SeatingCapacity TEXT,
    AgeGroup TEXT,
    FamilySize TEXT,
    SumInsuredBand TEXT,
    PreExiting TEXT,
    Occupancy TEXT,
    LifeGroup TEXT,
    Zone TEXT,
    Region TEXT,
    RenewalYearCount TEXT,
    Preferred TEXT,
    Activity TEXT,
    SubActivity TEXT,
    Amount TEXT,
    SMCode TEXT,
    SMName TEXT,
    SMBranch TEXT,
    SMBranchName TEXT,
    NCBFlag TEXT,
    MothYear TEXT,
    RenewalPaymentLink TEXT
);

''';

  static const dropLeadDetails = '''
  DROP TABLE IF EXISTS LeadDetails
''';

  static const dropLMSLeadActivityTracker = '''
  DROP TABLE IF EXISTS LMSLeadActivityTracker
''';

  static const lmsLeadActivityTracker = '''
CREATE TABLE IF NOT EXISTS LMSLeadActivityTracker(
    RecId integer primary key autoincrement,
    CltCode varchar,
    SrvcReqDtlCode varchar,
    ActivityCode varchar,
    SubActivityCode varchar,
    AppointmentDate varchar,
    Hour varchar,
    Minute varchar,
    AppointmentAddrss varchar,
    AppThrough varchar,
    ResThrough varchar,
    RescheduleDate varchar,
    RescheduleAddrss varchar,
    ParkedLead varchar,
    ProposalNo varchar,
    IssuedPolicyNo varchar,
    PremiumCollected varchar,
    AppReason varchar,
    SubReason varchar,
    DuplicateLeadId varchar,
    ComptitorID varchar,
    LocationDtls varchar,
    NonContble varchar,
    NotIntrest varchar,
    PhoneNumber varchar,
    CreateBy varchar,
    CreateDTim varchar,
    UpdateBy varchar,
    UpdateDTim varchar,
    IsActive varchar,
    oriPREMCOL varchar,
    MakenModel varchar,
    ExpiryDate varchar,
    CallBackDate varchar,
    TelesaleActivity varchar,
    TelesaleActivityDate varchar,
    InfectionID varchar,
    TicketNo varchar,
    QuoteNo varchar,
    LcReason varchar,
    LcSubReason varchar,
    Age varchar,
    RtoLoc varchar,
    Price varchar,
    YOM varchar,
    PED varchar,
    Feature varchar,
    Area varchar,
    PHC_NO varchar,
    ProductType varchar,
    Lan varchar,
    PostPQuery varchar,
    NotEligible varchar,
    Reason varchar,
    RsReason varchar,
    ModelValue varchar,
    NonContactableDtm varchar,
    CallBackDateRenewal varchar,
    NonConRes varchar,
    ChequeNo varchar,
    ChequeDate varchar,
    ChequeBankName varchar,
    RegistrationNo varchar,
    RenewalLeadLostReason varchar,
    PolicyAlreadyRenewedReason varchar,
    ParkedLeadDateTime varchar,
    FollowupDt varchar,
    QutationDt varchar,
    ddlAct16Subreason varchar,
    txt416 varchar,
    txtAD16 varchar,
    txtPN16 varchar,
    txt316 varchar,
    ddlMakeModel516 varchar,
    ddlModel616 varchar,
    txt716 varchar,
    txt816 varchar,
    ddlAppReasonTrack5 varchar,
    ddlSubReason varchar,
    txtDuplicateLeadId varchar,
    ddlCompetitorList varchar,
    txtLocationDtls varchar,
    txtTctNoact5 varchar,
    txtAge varchar,
    txtArea2 varchar,
    ddlRTOLoc varchar,
    txtPhcNo varchar,
    txtPrice varchar,
    txtPrdType varchar,
    txtYOM varchar,
    txtPed2 varchar,
    txtLanguage varchar,
    ddlMakeModelact5 varchar,
    txtReason5 varchar,
    txtCallBakDateTime19 varchar,
    txtPN19 varchar,
    txt319 varchar,
    txtRMSAppointmentDate varchar,
    txtRMSCallBackDate varchar,
    ddlRMSNonContactableReason varchar,
    txtRMSChequeNo varchar,
    ddlRMSRenewalLeadLostReason varchar,
    ddlRMSPolicyAlreadyRenewedReason varchar,
    txtRMSMobileNo varchar,
    txtAppointmentDate27 varchar,
    txtRescheduletDate28 varchar,
    ddlAppReasonTrack29 varchar,
    txtPolicyNo30 varchar,
    txtParkedLead31 varchar,
    txtFollowup32 varchar,
    txtQutation33 varchar,
    nInstrumentType varchar,
    nLcPolicyNumber varchar,
    nScPolicyNumber varchar,
    nScInstrumentNo varchar,
    nScInstrumentAmt varchar,
    nCallBackDate varchar,
    nExpectedClosureDate varchar,
    nLostCompDueTo varchar,
    nLlPolicyNoCompetition varchar,
    nCmpNameCompetition varchar,
    nNewPolEndDate varchar,
    internalcomment varchar,
    SyncStatus varchar,
    InstType varchar,
    LstComDueTo varchar,
    NewPolEndDate varchar,
    Remark varchar,
    TempSrvcReqDtlCode varchar
);

''';
}
