class DbTables {
  static const createUserTable = '''
    CREATE TABLE IF NOT EXISTS iUser(
        	SrNo integer primary key autoincrement,
        	UserId varchar,
        	UserName varchar,
        	UserEmailID varchar,
        	PhoneNo varchar,
        	UserPin varchar,
        	AuthType varchar,
        	LastAccessDate varchar,
        	RememberLogin varchar,
        	Password varchar,
        	UserStatus varchar,
        	memcode varchar,
        	Bizsrc varchar,
        	Chncls varchar,
        	CmsUnitCode varchar,
        	BranchName varchar,
        	Createddtim varchar,
        	Createdby varchar,
        	change_ver varchar,
        	TokenId varchar,
          UserType varchar,
          DashboardUpdatedDate varchar,
          CalendarUpdatedDate varchar,
          MobileNo varchar,
          EmailID varchar,
          Privacy_Flag varchar,
          Schedule_Days varchar,
          Ren_Rem_Days varchar
        );
  ''';

  static const dropUserTable = '''
    DROP TABLE IF EXISTS iUser
  ''';

  static const createTbl_DashboardData_Mob = '''
    CREATE TABLE IF NOT EXISTS DashboardData_Mob(
            RecId integer primary key autoincrement,
            UserId TEXT,
            AgentCode TEXT,
            AgentName TEXT,
            HNINCode TEXT,
            HNINName TEXT,
            LOBCode TEXT,
            ProdCode TEXT,
            NCBFlag TEXT,
            date TEXT,
            DateInLong LONG,
            TotalLeads TEXT,
            WIPLeads TEXT,
            LeadConverted TEXT,
            LeadLost TEXT,
            Lead_Converted TEXT,
            Premium_Collected TEXT,
            Policy_Issued TEXT,
            Call_Back TEXT,
            Appointment_Fixed TEXT,
            Non_Contactable TEXT,
            Lost_To_Competition TEXT,
            Customer_Not_Interested TEXT,
            Customer_Not_Responding TEXT,
            ParkLead TEXT,
            FollowUp TEXT,
            LeadType TEXT,
            BizType TEXT,
            MarcketType TEXT,
            PolicyChanel TEXT,
            BMCMCode TEXT,
            ircCode TEXT,
            ircname TEXT,
            RNType TEXT,
            NetODPremium TEXT,
            NetTPPremium TEXT,
            RNblockReason TEXT,
            ProductGroup TEXT,
            ProductSubCategory TEXT,
            NILDep TEXT,
            Category TEXT,
            FuelType TEXT,
            VehicleType TEXT,
            SeatingCapacity TEXT,
            AgeGroup TEXT,
            FamilySize TEXT,
            SumInsuredBand TEXT,
            PreExiting TEXT,
            Occupancy TEXT,
            SumInsured TEXT,
            LifeGroup TEXT,
            Zone TEXT,
            Region TEXT,
            RenewalYearCount TEXT,
            Preferred TEXT,
            Activity TEXT,
            SubActivity TEXT,
            Amount TEXT,
            SMName TEXT,
            SMBranch TEXT,
            SMBranchName TEXT,
            CreatedBy TEXT,
            CreateDTime TEXT,
            UpdatedBy TEXT,
            UpdatedDtime TEXT,
            MothYear TEXT,
            ReferenceNo varchar,
            SyncStatus varchar
          );
''';

  static const dropDashboardData_Mob = '''
    DROP TABLE IF EXISTS DashboardData_Mob
  ''';

  static const createTbl_CalendarData_Mob = '''
    CREATE TABLE IF NOT EXISTS CalendarData_Mob(
            RecId integer primary key autoincrement,
            UserId TEXT,
            AgentCode TEXT,
            AgentName TEXT,
            HNINCode TEXT,
            HNINName TEXT,
            LOBCode TEXT,
            ProdCode TEXT,
            NCBFlag TEXT,
            date TEXT,
            DateInLong LONG,
            TotalLeads TEXT,
            WIPLeads TEXT,
            LeadConverted TEXT,
            LeadLost TEXT,
            LeadType TEXT,
            BizType TEXT,
            MarcketType TEXT,
            PolicyChanel TEXT,
            BMCMCode TEXT,
            ircCode TEXT,
            ircname TEXT,
            RNType TEXT,
            NetODPremium TEXT,
            NetTPPremium TEXT,
            RNblockReason TEXT,
            ProductGroup TEXT,
            ProductSubCategory TEXT,
            NILDep TEXT,
            Category TEXT,
            FuelType TEXT,
            VehicleType TEXT,
            SeatingCapacity TEXT,
            AgeGroup TEXT,
            FamilySize TEXT,
            SumInsuredBand TEXT,
            PreExiting TEXT,
            Occupancy TEXT,
            SumInsured TEXT,
            LifeGroup TEXT,
            Zone TEXT,
            Region TEXT,
            RenewalYearCount TEXT,
            Preferred TEXT,
            SMName TEXT,
            SMBranch TEXT,
            SMBranchName TEXT,
            CreatedBy TEXT,
            CreateDTime TEXT,
            UpdatedBy TEXT,
            UpdatedDtime TEXT,
            mdate varchar,
            ReferenceNo varchar,
            SyncStatus varchar);
''';

  static const dropCalendarData_Mob = '''
    DROP TABLE IF EXISTS CalendarData_Mob
  ''';
}
